# Project Information
site_name: DevFrank Wiki
site_description: DevFrank Wiki是一个知识库整合站点
site_author: DevFrank
site_url: https://frankwang98.github.io/wiki/
repo_url: https://github.com/frankwang98/wiki
strict: false

# Copyright
copyright: Copyright &copy; 2022 - 2024 DevFrank

# Contents 导航栏
nav:
  - 简介: index.md
  - C++基础: 
    - 环境配置与基础语法: cpp_basic/C++环境配置与基础语法.md
    - 标准库: cpp_basic/C++标准库.md
    - 开源库: cpp_basic/C++开源库.md
    - 文件IO: cpp_basic/C++文件IO.md
    - 字符串: cpp_basic/C++字符串.md
    - 异常处理: cpp_basic/C++异常处理.md
    - 数组指针: cpp_basic/C++数组指针.md
    - 并发编程: cpp_basic/C++并发编程.md
    - 网络编程: cpp_basic/C++网络编程.md
    - 模板编程: cpp_basic/C++模板.md
    
  - C++数据结构与算法:
    - 排序算法: cpp_algorithm/排序算法.md
    - 查找算法: cpp_algorithm/查找算法.md
    - 链表: cpp_algorithm/链表.md
    - 设计模式: cpp_algorithm/设计模式.md
  
  - C++开源库和框架:
    - jsoncpp解析库: cpp_library/jsoncpp解析库.md
    - rapidjson解析库: cpp_library/rapidjson解析库.md
    - cjson解析库: cpp_library/cjson解析库.md
    - tinyxml2解析库: cpp_library/tinyxml2解析库.md
    - fast-cpp-csv-parser解析库: cpp_library/fast-cpp-csv-parser解析库.md
    - easylogging++日志库: cpp_library/easylogging++日志库.md
    - spdlog日志库: cpp_library/spdlog日志库.md
    - zeromq消息队列库: cpp_library/zeromq消息队列库.md
    - vsomeip消息队列库: cpp_library/vsomeip消息队列库.md
    - ffmpeg音视频库: cpp_library/ffmpeg音视频库.md
    - vulkan图形学库: cpp_library/vulkan图形学库.md

  - C++Qt嵌入式与桌面应用:
    - Qt环境安装与基础示例: cpp_qt/Qt环境安装与基础示例.md
    - vs2017+qt环境配置: cpp_qt/vs2017+qt环境配置.md
    - qml环境配置: cpp_qt/qml环境配置.md
    - QWidget与注册登陆界面: cpp_qt/QWidget与注册登陆界面.md
    - Qt事件与正弦曲线绘制示例: cpp_qt/Qt事件与正弦曲线绘制示例.md
    - QCustomPlot图表绘制库: cpp_qt/QCustomPlot图表绘制库.md
    - SQLite数据库示例: cpp_qt/SQLite数据库示例.md
    - 获取系统和网络信息示例: cpp_qt/获取系统和网络信息示例.md
    - 串口调试助手示例: cpp_qt/串口调试助手示例.md
    - CAN分析仪二次开发示例: cpp_qt/CAN分析仪二次开发示例.md
    - TCP+UDP网络通信示例: cpp_qt/TCP+UDP网络通信示例.md
    - windeployqt+nsis程序打包和发布: cpp_qt/windeployqt+nsis程序打包和发布.md
    - wxGlade配置与使用: cpp_qt/wxGlade配置与使用.md

  - C++ROS机器人与自动驾驶:
    - ROS环境安装与基础示例: cpp_ros/ROS环境安装与基础示例.md

  - C++CV计算机视觉:
    - OpenCV环境安装与基础示例: cpp_cv/OpenCV环境安装与基础示例.md
    - 图像视频读取基础操作: cpp_cv/图像视频读取基础操作.md
    - 车道线检测原理与实现示例: cpp_cv/车道线检测原理与实现示例.md
    - YOLO目标检测介绍及实现示例: cpp_cv/YOLO目标检测介绍及实现示例.md
    - 红绿灯检测及实现示例: cpp_cv/红绿灯检测及实现示例.md

  - C++GL图形学与游戏:
    - OpenGL环境安装与基础示例: cpp_gl/OpenGL环境安装与基础示例.md
    - 创建线段和多边形示例: cpp_gl/创建线段和多边形示例.md

  - Shell脚本与自动化:
    - Python环境安装与基础示例: shell_python/Python环境安装与基础示例.md

  # - 语言基础:
  #   - STM32: ./Econtrol/1-stm32.md
  #   - C/CPP: ./Econtrol/2-cpp.md
  #   - Python: ./Econtrol/3-python.md
  # - 库和框架: 
  #   - Qt: ./Application/1-qt.md
  #   - Shell: ./Application/2-linux.md
  #   - ROS: ./Application/3-ros.md
  # - 数据结构与算法: 
  #   - Vision: ./AI/1-vision.md
  #   - PointCloud: ./AI/2-pointcloud.md
  #   - Fusion: ./AI/3-fusion.md
  # - 工具: 
  #   - 工具: ./Other/toolbox.md
  #   - 资源: ./Other/study.md
  # - 关于: about.md 

# 主题
# theme: material # readthedocs material darkly bootswatch

# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - content.code.annotate 
    - navigation.top
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# 插件
# plugins:
#   - search
#   - awesome-pages
#   - markdown-code-blocks

plugins: []
  
# markdown
markdown_extensions:
  - smarty
  - codehilite
  - toc:
      permalink: false
  - mdx_math:
      add_preview: true
      enable_dollar_delimiter: true