name: wiki_ci 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material python-markdown-math

      - name: Git clone
        run: git clone https://github.com/squidfunk/mkdocs-material

      - name: Deploy
        run: mkdocs gh-deploy --force